- name: NGINX
  hosts: h4p
  gather_facts: true

  tasks:
    - name: APT update
      ansible.builtin.apt:
        update_cache: true

    - name: Install NGINX
      ansible.builtin.apt:
        name: nginx

    - name: Copy SSL options
      ansible.builtin.copy:
        src: nginx/options-ssl.conf
        dest: /etc/nginx/options-ssl.conf
        mode: preserve

    - name: Copy static id.h4p
      ansible.builtin.copy:
        src: www/id
        dest: /var/www
        mode: preserve

    - name: Copy config id.h4p
      ansible.builtin.copy:
        src: nginx/id.conf
        dest: /etc/nginx/sites-available/id
        mode: preserve

    - name: Enable id.h4p
      ansible.builtin.file:
        src: /etc/nginx/sites-available/id
        dest: /etc/nginx/sites-enabled/id
        state: link

    - name: Copy config elf-pavlik.h4p
      ansible.builtin.copy:
        src: nginx/elf-pavlik.conf
        dest: /etc/nginx/sites-available/elf-pavlik
        mode: preserve

    - name: Enable elf-pavlik.h4p
      ansible.builtin.file:
        src: /etc/nginx/sites-available/elf-pavlik
        dest: /etc/nginx/sites-enabled/elf-pavlik
        state: link

    - name: Copy config samurex.h4p
      ansible.builtin.copy:
        src: nginx/samurex.conf
        dest: /etc/nginx/sites-available/samurex
        mode: preserve

    - name: Enable samurex.h4p
      ansible.builtin.file:
        src: /etc/nginx/sites-available/samurex
        dest: /etc/nginx/sites-enabled/samurex
        state: link


- name: Certbot
  hosts: h4p
  gather_facts: true

  vars:
    certbot_admin_email: elf-pavlik@hackers4peace.net
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - domains:
          - id.hackers4peace.net
      - domains:
          - elf-pavlik.hackers4peace.net
      - domains:
          - samurex.hackers4peace.net

  pre_tasks:
    - name: Install cron
      ansible.builtin.apt:
        name: cron
        state: present

  roles:
    - geerlingguy.certbot

  tasks:
    - name: Flush handlers in case any configs have changed.
      ansible.builtin.meta: flush_handlers

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Test secure connection to SSL domain.
      ansible.builtin.uri:
        url: https://elf-pavlik.hackers4peace.net/
        status_code: 200
      delegate_to: localhost
      become: false
